name: Sync README.md from Project A

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout project-b
        # Use the default GITHUB_TOKEN for actions within this repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Get README.md from Project A
        run: |
          # Use your PAT to fetch the file from project-a
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 https://oauth2:${{ secrets.PROJECT_A_TOKEN }}@github.com/shivam-work-name/project-a.git main
          
      - name: Checkout the README.md file
        run: git checkout FETCH_HEAD -- README.md

      - name: Check for changes and commit
        id: commit-file
        run: |
          if [[ -n $(git status --porcelain README.md) ]]; then
            git add README.md
            git commit -m "feat(sync): Update README.md from project-a"
            # The push now works because we're using the GITHUB_TOKEN
            git push
            echo "::notice::README.md has been successfully updated and pushed."
          else
            echo "::notice::No changes detected in README.md. Nothing to commit."
          fi
